spring.application.name=notification-service
server.port=8082
spring.cloud.consul.host=project_consul
spring.cloud.consul.port=8500
spring.cloud.consul.discovery.health-check-path=/actuator/health
spring.cloud.consul.discovery.health-check-interval=10s
spring.mail.host=smtp.gmail.com
spring.mail.port=587
#spring.mail.username=sheevani433@gmail.com
#spring.mail.password=iijpyeedskkrfbqe


# Force registration with IP instead of Hostname
spring.cloud.consul.discovery.prefer-ip-address=true

# (Optional but recommended) explicitly ignore the mshome.net domain
spring.cloud.inetutils.ignored-interfaces=mshome.*

spring.mail.username=joladpavankumar@gmail.com
spring.mail.password=njgpuwrueoslfssx
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
management.endpoints.web.exposure.include=health,info
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.maail.smtp.ssl.trust=smtp.gmail.com