services:

  postgres:
    image: postgres:15-alpine
    container_name: project_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: api_db
    ports:
      - "5432:5432"

  zookeeper:
    image: confluentinc/cp-zookeeper:7.6.1
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    ports:
      - "2181:2181"
    networks:
      - project-network

  kafka:
    image: confluentinc/cp-kafka:7.6.1
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - project-network
  consul:
    image: hashicorp/consul:latest
    container_name: project_consul
    command: "agent -dev -client=0.0.0.0"
    ports:
      - "8500:8500"

  user-service:
    image: eclipse-temurin:21-jdk-alpine
    container_name: user_service
    command: ["java","-jar","/app/user-service-0.0.1-SNAPSHOT.jar"]
    volumes:
      - ./user-service/target/user-service-0.0.1-SNAPSHOT.jar:/app/user-service-0.0.1-SNAPSHOT.jar
    environment:
      - SERVER_PORT=8081
      - SPRING_DATASOURCE_URL=jdbc:postgresql://project_db:5432/api_db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=root
      - SPRING_CLOUD_CONSUL_HOST=project_consul   # ✅ fix consul host
      - SPRING_CLOUD_CONSUL_PORT=8500
    ports:
      - "8081:8081"
    depends_on:
      postgres:
        condition: service_healthy        # ✅ wait until postgres is ready
      consul:
          condition: service_healthy

  notification-service:
    image: eclipse-temurin:21-jdk-alpine
    container_name: notification_service
    command: ["java","-jar","/app/notification-service-0.0.1-SNAPSHOT-exec.jar"]
    volumes:
      - ./notification-service/target/notification-service-0.0.1-SNAPSHOT-exec.jar:/app/notification-service-0.0.1-SNAPSHOT-exec.jar
    environment:
      - SERVER_PORT=8082
      - SPRING_CLOUD_CONSUL_HOST=project_consul   # ✅ fix consul host
      - SPRING_CLOUD_CONSUL_PORT=8500
    ports:
          - "8082:8082"
    networks:
          - project-network
    depends_on:
        consul:
          condition: service_healthy


  api-gateway:
    image: eclipse-temurin:21-jdk-alpine
    container_name: api_gateway
    command: [ "java","-jar","/app/apiGatewayService-0.0.1-SNAPSHOT.jar" ]
    volumes:
      - ./apiGatewayService/target/apiGatewayService-0.0.1-SNAPSHOT.jar:/app/apiGatewayService-0.0.1-SNAPSHOT.jar
    environment:
      - SERVER_PORT=8080
      - SPRING_CLOUD_CONSUL_HOST=project_consul   # ✅ fix consul host
      - SPRING_CLOUD_CONSUL_PORT=8500
    ports:
      - "8080:8080"
    networks:
      - project-network
    depends_on:
      user-service:
        condition: service_started
      notification-service:
        condition: service_started

networks:
  project-network:
    driver: bridge