spring.application.name=user-service
server.port=8081

## CONSUL
#spring.cloud.consul.host=project_consul
#spring.cloud.consul.port=8500
#spring.cloud.consul.discovery.register=true
#spring.cloud.consul.discovery.enabled=true
#spring.cloud.consul.discovery.health-check-path=/actuator/health
#spring.cloud.consul.discovery.health-check-interval=10s
#spring.cloud.consul.discovery.prefer-ip-address=true
#spring.cloud.inetutils.ignored-interfaces=mshome.*

## ACTUATOR
#management.endpoints.web.exposure.include=health,info

# KAFKA PRODUCER (container -> use kafka:9092)
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
spring.kafka.producer.acks=all
spring.kafka.producer.retries=3

# TOPIC
app.kafka.topic=notification-events

spring.datasource.url=jdbc:postgresql://localhost:5432/user
spring.datasource.username=postgres
spring.datasource.password=Sony
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect